# Generated by Django 3.0.6 on 2020-05-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_age', models.IntegerField()),
                ('cat_img', models.ImageField(upload_to='uploads/')),
                ('cat_paragraph', models.CharField(max_length=1000)),
                ('date_entered', models.DateTimeField()),
            ],
        ),
    ]
