# Generated by Django 3.0.6 on 2020-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadrivenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_age', models.IntegerField()),
                ('pet_img', models.ImageField(upload_to='uploads/')),
                ('pet_paragraph', models.CharField(max_length=1000)),
                ('date_entered', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
