# Generated by Django 3.0.6 on 2020-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadrivenapp', '0002_auto_20200517_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.CharField(max_length=2),
        ),
    ]
